### ISSUE TITLE
Domain expired

### ISSUE THREAD

**Issue by damianofalcioni** [stackgl/stackgl.github.io#11]
Hi,
your domain stack.gl has expired.
bye,
Damiano

**Comment by idflood** [comment]
One "workaround" is to add the following in your `/etc/hosts`. It will make the stack.gl directly point to the github.io server where the site is hosted.

    185.199.108.153 stack.gl

**Comment by dy** [comment]
@chrisdickinson @bpostlethwaite @Erkaman @gre @hughsk @gregtatum do you guys have access to hosting to renew the domain? I will remove CNAME for now.

**Comment by hughsk** [comment]
I believe @mikolalysenko owns the domain, but not sure if anybody else has access to the account. iirc it's relatively expensive (>$100USD/yr). Right now I'm only working 1 day/week but I should be able to chip in or cover the cost in October once I'm working FT again. We should probably switch to https://stackgl.github.io as the primary URL regardless :)
