### ISSUE TITLE
glsl.io is spam website now

### ISSUE THREAD

**Issue by AskAlice** [stackgl/stackgl.github.io#15]
I would put in a PR but the examples.md needed to build is missing from this repository

**Comment by AskAlice** [comment]
gl-transitions is the proper name of glsl.io now, It is located at https://gl-transitions.com/

Perhaps this project just needs to be rebuilt and pushed?

**Comment by gre** [comment]
Thanks @AskAlice 

@hughsk hey mate, are you in control of the stack.gl hosting? (Does it automatically deploy if we merge things in?). Thanks

**Comment by AskAlice** [comment]
@gre @hughsk @dhritzkiv @kevzettler could one of you just rebuild this repo and push it upstream? You're just throwing money at a domain squatter while leaving the original author in the dust by leaving it like this for so long.

**Comment by kevzettler** [comment]
@AskAlice hi i'm new to the project and need more context here. Can you point me in the code to where this `glsl.io` link needs to be updated? Sounds like maybe this belongs in the https://github.com/stackgl/packages repo?

**Comment by kevzettler** [comment]
appears fixed with
https://github.com/stackgl/stackgl.github.io/pull/17
