### ISSUE TITLE
modules / organization

### ISSUE THREAD

**Issue by mattdesl** [stackgl/stackgl.github.io#3]
I think it would be good to impose a bit of structure and forethought into some modules that we know are going to be part of the stackgl ecosystem. For the most part there is no "core" since it depends on your needs, but there are modules like `gl-texture2d` which will make up other modules (like `gl-fbo`) and there are also higher level abstractions that may make the low-level stuff less necessary for the average developer (like `gl-geometry` over `gl-vao`/`gl-buffer`). 

This is mostly just a place to spitball ideas, API structure, naming style, etc.

#### cameras

This is a common thing that ends up getting repeated in pretty much every demo / test I write. Some discussion/experimentation already [going on here](https://github.com/mikolalysenko/3d-camera-core), hopefully we can think about 2D cameras as well. These will help bring newbies to the project since a lot of people are not comfortable working with 4x4 matrices.

#### camera controls

This is related, but something to keep in mind when building out 3d-camera-core. ThreeJS has some really sprawling and monolithic orbit/FPS/etc controls that are hard to build on. Things like [canvas-orbit-camera](https://www.npmjs.com/package/canvas-orbit-camera) are great for tests and prototyping, but not as suitable for production where you will want to ease/swing the camera and rotations. I'm pretty confident we can get a variety of awesome "drop-in" controls using [eases](https://www.npmjs.com/package/eases), Catmull-Rom splines, etc. In an ideal world these would just operate on matrices or simple structs, so that they could end up working with ThreeJS/Pex/etc.

#### 2D/3D abstractions

I've already got a bunch of high level modules like [gl-vignette-background](https://github.com/mattdesl/gl-vignette-background) and [gl-sprite-batch](https://www.npmjs.com/package/gl-sprite-batch) that are starting to form a few conventions. These are well outside the "core" or "sanctioned" part of stackgl, but important for attracting newcomers that don't want to think so much about shaders, buffers, matrices, etc. It's also great for [prototyping](http://mattdesl.github.io/impressionist-3d/3d.html) since there's often no need to drop down too low-level.

I am thinking of running a little further with the ["sprite"](https://github.com/mattdesl/gl-sprite-batch) idea for 2D applications; a generic quad with color/texture/texcoord/shape/position. Would appreciate some feedback though; it's very specific and "frameworky" compared to the n-dimensional approach that most stackgl modules take right now. 

#### post-processing

A pipeline of sorts for post-processing would be nice: [discussion](https://github.com/stackgl/gl-post/issues/2).

Could also start working with "drop in" shaders like `gl-shader-fxaa`, `gl-shader-grayscale` etc. Or maybe these should be differently named to identify them as `gl-post` type of shaders? 

#### glsl blend modes

There's two facets to this: porter-duff compositing (src-over, dest-in, etc) and then "blend modes" like color dodge, screen, overlay, etc. These can be published to separate modules, and we can leverage some code from [here](https://mouaif.wordpress.com/2009/01/05/photoshop-math-with-glsl-shaders/) or [here](http://wwwimages.adobe.com/www.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/PDF32000_2008.pdf) (11.3.5 - page 332). In terms of names and API, they should all be consistent for discoverability, e.g.:

```
 glsl-blend-src-over
 glsl-blend-overlay
 glsl-blend-soft-light
```

**Comment by hughsk** [comment]
@mattdesl +1 to all of this. I'm caught up with glslify v2 so it'll be a little while before I can start chipping in on this stuff, but getting there :)

My biggest interest is in improving the workflow for prototyping, and getting stuff on the screen as quickly as possible for people to play around and experiment with. Though I have some reservations about boilerplates, I think it'd be great to have a base project with glslify/browserify/etc. all set up, and glslify-live once it's working again too.

One easy win would be to improve the `*-orbit-camera` modules for nicer interaction. I think if we made it more sensitive and add a bit of easing, it'd make a huge difference to all of the demos which rely on it.

@mikolalysenko and I were also chatting about getting some (optional) three.js-like abstractions: one or more scene graph modules, and a wrapper for `gl-matrix` for nicer transformations (maybe [vecmath](https://github.com/mattdesl/vecmath)?).

I was also thinking we should use [stackgl/contributing](http://github.com/stackgl/contributing) as a module wishlist, i.e. open up issues for discussion but also a source of ideas for contributors who want to help out but don't know where to start. What do you reckon?

**Comment by mattdesl** [comment]
:+1: to your points. A scene graph would be good to have. 

I'd be curious to see ideas about how to revive or better implement `vecmath`. I've moved away from objects/classes since they are not easy to re-use, and I'm not sure if we should be encouraging newbies any practices that we wouldn't want to do ourselves.

**Comment by hughsk** [comment]
Yeah, so there's definitely mixed feelings about wrappers like that. I personally still just use `gl-matrix` in my stuff, though I think if somebody wants to use one in their application that's ok. Maybe it's a good compromise if we suggest using `gl-matrix` in modules/libraries, and using a wrapper is an option when building out projects/demos? Would be a good place to put an explanation on why we normally go for plain arrays too :)

**Comment by mikolalysenko** [comment]
I've been wrestling with this problem a lot lately, largely on behalf of plotly and in the interest of trying to make a really high quality camera module (both from the perspective of user experience and reusability).

Since it is one of those things that comes up in almost every 3D project, I really want to get this right and make something that will work.

After a lot of back and forth, the way I am thinking about doing this now is to have one generic camera module which handles coordinate transformations and access to common bits of geometry, and then use separate modules to implement functionality like perspective transformations.

**Comment by mattdesl** [comment]
ok, further discussion on modules / etc can go into [contributing](https://github.com/stackgl/contributing/issues)
