### ISSUE TITLE
Hello stackgl community - Plotly loves you folks! 

### ISSUE THREAD

**Issue by bpostlethwaite** [stackgl/stackgl.github.io#6]
@stackgl/owners and @stackgl/collaborators 
Hello fellow Stackers! 

Plotly has recently gone [open source](https://github.com/plotly/plotly.js) bringing [Stackgl into many new hands](https://plot.ly/javascript/). We are looking for someone to help us introduce Stackgl to even more developers and users by continuing to push the 2D webgl plotting capacities of [gl-vis](https://github.com/gl-vis) forward. We envision [gl-vis](https://github.com/gl-vis) as a fully featured open source webgl plotting framework with the same high level set of interactions and detail folks expect from Plotly.

I have had the pleasure of working with @mikolalysenko over the last year and half and am looking forward to meeting others in the stackgl community.

If you are interested in freelance open source work that utilizes the stackgl 'stack' send me an email! We would love to get started on this right away.

I won't be abusing github issues to make announcements and introductions again so even if you are a little busy right now feel free to drop me an email to say hi. I'll show up on IRC at some point over the holidays to see who is hanging around.

cheers and happy holidays!

ben at plot.ly

**Comment by kumavis** [comment]
thanks for contributing to the community

**Comment by hughsk** [comment]
stack.gl loves plot.ly :sparkling_heart: Thanks for your contributions and support! Will let you know if I find anybody who's available :)

**Comment by gre** [comment]
cool :+1:

**Comment by mattdesl** [comment]
:heart: 

Thanks!
