### ISSUE TITLE
Add missing packages

### ISSUE THREAD

**Issue by rreusser** [stackgl/stackgl.github.io#8]
I'll PR this shortly, but the first step is just to catch missing stack.gl-appropriate packages. Open to feedback on whether to transfer them to stack.gl ownership or just link externally. I'm glad to transfer mine or make any other changes.

- [glsl-solid-wireframe](https://github.com/rreusser/glsl-solid-wireframe)
- [glsl-domain-coloring](https://github.com/rreusser/glsl-domain-coloring)
- [glsl-godrays](https://github.com/Erkaman/glsl-godrays)
- [glsl-cos-palette](https://github.com/Erkaman/glsl-cos-palette)
- [glsl-gradient-palette](https://github.com/Erkaman/glsl-gradient-palette)
- [glsl-worley](https://github.com/Erkaman/glsl-worley)
- [glsl-sat](https://github.com/realazthat/glsl-sat)
- [glsl-numerify](https://github.com/realazthat/glsl-numerify)
- [glsl-quad](https://github.com/realazthat/glsl-quad)
- [glsl-gaussian](https://github.com/realazthat/glsl-gaussian)
- [glsl-zoom](https://github.com/realazthat/glsl-zoom)
- glsl-ssao: I have a rough SSAO implementation put together as does @vorg, but I'm not sure either is quite fit for publishing yet (at least mine's not). But maybe it'd be worthwhile to assemble that into something publishable.

No obligation to add, depending on people's preferences. Will add others to this list and then try moving to PR. If you know of other missing packages or people likely to know where there may be more, please suggest/cc!

cc @gregtatum @vorg @Erkaman @realazthat

**Comment by gregtatum** [comment]
It'd be nice to do a search through: https://www.npmjs.com/browse/keyword/stackgl and see what we are missing as well.

**Comment by Erkaman** [comment]
:D

**Comment by derhuerst** [comment]
@stultiloquence wrote [`birds-eye-camera`](https://github.com/stultiloquence/birds-eye-camera), a slightly different alternative to [`first-person-camera`](https://github.com/shama/first-person-camera). We might add that as well. (:

**Comment by rreusser** [comment]
Another? https://github.com/cabbibo/glsl-curl-noise

**Comment by rreusser** [comment]
At least one more, once published: [glsl-fft](https://github.com/rreusser/glsl-fft).

And this time, will actually update the site in the next day or two…

**Comment by rreusser** [comment]
And: https://github.com/substack/screen-projected-lines

**Comment by rreusser** [comment]
Also @gregtatum's [quads](https://github.com/gregtatum/quads) (if that's okay, @gregtatum?)

**Comment by gregtatum** [comment]
Of course!

**Comment by MaxBittker** [comment]
oh, this is awesome 💯

**Comment by kevzettler** [comment]
Looks like most of these have been added and published in 
https://github.com/stackgl/packages/wiki/Packages

**Comment by rreusser** [comment]
Thanks so much @kevzettler !!
